-- ============================================================
-- Migration: clinics.code + public.staff_usernames
-- Purpose:
--   - clinics.code  : stable unique short code for username prefixes
--   - staff_usernames : per-clinic username → auth user_id mapping
--     (used ONLY by server login resolution; never read by client)
-- ============================================================

BEGIN;

-- ── 1. clinics.code ────────────────────────────────────────
-- Stable clinic code like 'SM4827' used as username prefix.
-- Generated by the app at clinic creation time (not by DB default),
-- then stored here so username prefixes are stable and unique.

ALTER TABLE public.clinics
  ADD COLUMN IF NOT EXISTS code TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_clinics_code_unique
  ON public.clinics (code)
  WHERE code IS NOT NULL;

-- ── 2. staff_usernames ─────────────────────────────────────
-- Mapping: clinic_id + username → auth user_id
-- Uniqueness: one username per clinic. Different clinics may reuse
-- the same username (e.g. both have a "manager") because prefix
-- differs by clinic code in practice.
--
-- Security: RLS on this table is restrictive. Client components must
-- NEVER read this table directly. All resolution happens in server
-- API routes via the service-role client or an authorized RPC.

CREATE TABLE IF NOT EXISTS public.staff_usernames (
  id           TEXT PRIMARY KEY DEFAULT gen_random_uid(),
  clinic_id    TEXT NOT NULL,
  username     TEXT NOT NULL,
  user_id      TEXT NOT NULL,           -- auth.users.id

  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_staff_usernames_clinic
    FOREIGN KEY (clinic_id)
    REFERENCES public.clinics(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_staff_usernames_user
    FOREIGN KEY (user_id)
    REFERENCES public.auth.users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- One username per clinic only
CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_usernames_clinic_username
  ON public.staff_usernames (clinic_id, username);

-- Fast lookup by username alone (used by login resolver, scoped by clinic)
CREATE INDEX IF NOT EXISTS idx_staff_usernames_username
  ON public.staff_usernames (username);

-- ── 3. RLS on staff_usernames ─────────────────────────────
-- No direct client access. We keep RLS enabled but allow the migration
-- runner / service role to manage rows. Client components MUST NOT
-- query this table. If you later expose any read, do it through an
-- authorized RPC only.

ALTER TABLE public.staff_usernames
  ENABLE ROW LEVEL SECURITY;

-- Allow service role / migration runner full access.
-- Authenticated app users do NOT get any direct access by default.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.staff_usernames TO service_role;
REVOKE ALL ON public.staff_usernames FROM anon, authenticated, public;

-- ── 4. Seed existing clinics with a code IF they don't have one ──
-- Only runs safely if code is NULL. Uses a deterministic short code
-- derived from id for existing clinics. New clinics should set code
-- explicitly at creation time from the registration flow.
--
-- NOTE: gen_random_uuid() is used only as a source of entropy for the
-- code suffix; the code format itself is 'CL' + 4 alphanumeric chars.

DO $$
DECLARE
  r RECORD;
  suffix TEXT;
BEGIN
  FOR r IN
    SELECT id FROM public.clinics WHERE code IS NULL
  LOOP
    -- 4 random alphanumeric chars from a uuid for stable uniqueness
    suffix := substring(replace(uuid_generate_v4()::text, '-', ''), 1, 4);
    UPDATE public.clinics
      SET code = 'CL' || suffix
      WHERE id = r.id;
  END LOOP;
END;
$$;

COMMIT;

-- ============================================================
-- Verification queries (run after applying):
--
-- \d public.clinics
-- \d public.staff_usernames
-- SELECT id, code FROM public.clinics LIMIT 5;
-- SELECT clinic_id, username, user_id FROM public.staff_usernames LIMIT 5;
--
-- Existing data should now have clinics.code filled (or NULL for
-- clinics created before this migration, until their code is set).
-- ============================================================
